name: Rate card creation
on:
  workflow_dispatch:
    inputs:
      city-name:
        description: City name
        required: true
        type: string
      cluster-name:
        description: Cluster name
        required: true
        type: string
      org-name:
        description: Organization name
        required: false
        type: string
      rate-card-file-link:
        description: Rate card file S3 link
        required: true
        type: string

jobs:
  create-rate-card:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: scripts/package-lock.json

      - name: Config git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"
          git branch -a

      - name: Create or switch to release branch
        id: create_branch
        run: |
          CURRENT_DATE=$(date +'%Y-%m-%d')
          echo "date=$CURRENT_DATE" >> $GITHUB_OUTPUT

      - name: Run main.js
        run: |
          cd scripts
          npm install
          npm start
        env:
          CITY_NAME: ${{ inputs.city-name }}
          CLUSTER_NAME: ${{ inputs.cluster-name }}
          ORG_NAME: ${{ inputs.org-name }}
          RATE_CARD_FILE_LINK: ${{ inputs.rate-card-file-link }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: 'release/rate-rule-${{ steps.create_branch.outputs.date }}-Auto'
          title: 'Auto PR for rate card on release/rate-rule-${{ steps.create_branch.outputs.date }}-Auto'
          body: 'This PR was automatically created by the GitHub Action.'
          labels: rate-card-automation

      - name: Merge pull request
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'release/rate-rule-${{ steps.create_branch.outputs.date }}-Auto',
              base: 'release/rate-rule-final',
              state: 'open'
            })
            if (pullRequests.length > 0) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pullRequests[0].number,
              })
            }
